### ISSUE TITLE
Breaking a locked double chest leaves a ghost block

### ISSUE THREAD

**Issue by cosmicgelatin** [MoonflowerTeam/locksmith#12]
### What version are you seeing the problem on?

1.18.2

### Describe the issue

```markdown
Placing a double chest then locking one of them (effectively both) causes them to leave ghost blocks when broken, basically never actually breaking them. Rejoining the server (restarting in singleplayer) shows that they never left. I only pasted the apparent error, as the log file was too long.
```

### latest.log

```shell
[15:42:09] [Server thread/ERROR]: Not a map: [I;-20,63,88]
[15:42:09] [Server thread/ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundPlayerActionPacket@1a8e890d, suppressing error
java.lang.RuntimeException: Not a map: [I;-20,63,88]
	at com.mojang.serialization.DataResult.lambda$getOrThrow$4(DataResult.java:100) ~[datafixerupper-4.1.27.jar%2333!/:?]
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[datafixerupper-4.1.27.jar%2333!/:?]
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93) ~[datafixerupper-4.1.27.jar%2333!/:?]
	at gg.moonflower.locksmith.common.lock.LockInteractionManager.onBreakBlock(LockInteractionManager.java:93) ~[locksmith-forge-1.0.2+1.18.2.jar%23129!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.handler$zld000$destroyBlock(ServerPlayerGameMode.java:523) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_9280_(ServerPlayerGameMode.java:258) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_9286_(ServerPlayerGameMode.java:224) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_7391_(ServerPlayerGameMode.java:194) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7502_(ServerGamePacketListenerImpl.java:952) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:34) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:8) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:762) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[15:42:12] [Server thread/ERROR]: Not a map: [I;-18,63,88]
[15:42:12] [Server thread/ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundPlayerActionPacket@7e0cbae9, suppressing error
java.lang.RuntimeException: Not a map: [I;-18,63,88]
	at com.mojang.serialization.DataResult.lambda$getOrThrow$4(DataResult.java:100) ~[datafixerupper-4.1.27.jar%2333!/:?]
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[datafixerupper-4.1.27.jar%2333!/:?]
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93) ~[datafixerupper-4.1.27.jar%2333!/:?]
	at gg.moonflower.locksmith.common.lock.LockInteractionManager.onBreakBlock(LockInteractionManager.java:93) ~[locksmith-forge-1.0.2+1.18.2.jar%23129!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.handler$zld000$destroyBlock(ServerPlayerGameMode.java:523) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_9280_(ServerPlayerGameMode.java:258) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_9286_(ServerPlayerGameMode.java:224) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_7391_(ServerPlayerGameMode.java:194) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7502_(ServerGamePacketListenerImpl.java:952) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:34) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:8) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:762) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23166!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by jacksonhardaway** [comment]
Could you upload your locksmithLocks.dat file from your world data folder?
